# Generated by Django 6.0.7 on 2026-09-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prize_pool',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
