# Generated by Django 6.0.3 on 2026-08-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='OTP',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
