# Generated by Django 6.0.3 on 2026-08-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('P', 'participant'), ('J', 'judge'), ('E', 'employee'), ('O', 'organizer')], max_length=12),
        ),
    ]
